APTestimonyBundle:
    resource: "../src/Routes/testimony/routing.yml"
    prefix:   /

APPhotoBundle:
    resource: "../src/Routes/photo/routing.yml"
    prefix:   /

APPageBundle:
    resource: "../src/Routes/page/routing.yml"
    prefix:   /

APQuotationBundle:
    resource: "../src/Routes/quotation/routing.yml"
    prefix:   /

APMusicBundle:
    resource: "../src/Routes/music/routing.yml"
    prefix:   /

APNewsBundle:
    resource: "../src/Routes/news/routing.yml"
    prefix:   /

APUserAdminBundle:
    resource: "../src/Routes/user/adminuser.yml"
    prefix:   /

APUserBundle:
    resource: "../src/Routes/user/user.yml"
    prefix:   /

Store:
    resource: "../src/Routes/store/routing.yml"
    prefix:   /