ap_mobile:
    resource: "../src/Routes/mobile/routing.yml"
    prefix:   /

ap_useful_link:
    resource: "../src/Routes/usefullink/routing.yml"
    prefix:   /

APFileManagementBundle:
    resource: "../src/Routes/filemanagement/routing.yml"
    prefix:   /

APTestimonyBundle:
    resource: "../src/Routes/testimony/routing.yml"
    prefix:   /

APPhotoBundle:
    resource: "../src/Routes/photo/routing.yml"
    prefix:   /

APPageBundle:
    resource: "../src/Routes/page/routing.yml"
    prefix:   /

APQuotationBundle:
    resource: "../src/Routes/quotation/routing.yml"
    prefix:   /

APPartnerBundle:
    resource: "../src/Routes/partner/routing.yml"
    prefix:   /

APMusicBundle:
    resource: "../src/Routes/music/routing.yml"
    prefix:   /

APDocumentBundle:
    resource: "../src/Routes/document/routing.yml"
    prefix:   /

APNewsBundle:
    resource: "../src/Routes/news/routing.yml"
    prefix:   /

APUserAdminBundle:
    resource: "../src/Routes/user/adminuser.yml"
    prefix:   /

APUserBundle:
    resource: "../src/Routes/user/user.yml"
    prefix:   /

Movie:
    resource: "../src/Routes/movie/routing.yml"
    prefix:   /

Store:
    resource: "../src/Routes/store/routing.yml"
    prefix:   /